spring:
  datasource:
    url: jdbc:h2:mem:desafio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  servlet:
    context-path: /api/v1
  port: 8080
